name: phishingMLP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - pandas
  - scikit-learn
  - numpy
  - pytorch==1.11.0
  - torchvision==0.12.0
  - torchaudio==0.11.0
  - seaborn
