name: phishingMLP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib==3.5.2
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - numpy==1.23.3
  - pytorch==1.11.0
  - torchvision==0.12.0
  - torchaudio==0.11.0
  - seaborn==0.12.0
